apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
     type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
  path: "/mnt/data"



