apiVersion: v1
kind: Service
metadata:
  name: result-svc
  labels: 
    name: result-svc
    app: result-svc
spec:
  selector:
    app: result-svc
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort  
