apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy 
  labels:
    name: web-deploy
    app: web-deploy
spec:
  selector:
    matchLabels:
      app: web-deploy
   
  template:
    metadata:
      labels:
        app: web-deploy
     
    spec:
      containers:
      - name: webserver
        image: fhalearslan/web-server:v1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: server-cm
        - secretRef:
            name: db-secret    

